### ISSUE TITLE
Message is not recognized correctly

### ISSUE THREAD

**Issue by vova-lantsov-dev** [volkovskey/exchange-rates-tg-bot#10]
Text: `инт32`
Expected: nothing happens
Actual: recognized as 32 BYN
<img width="367" alt="Screenshot 2021-08-16 at 19 32 25" src="https://user-images.githubusercontent.com/45858087/129597910-02c79892-a3d9-4854-8835-474a2b59ad03.png">

**Comment by volkovskey** [comment]
Fixed.
