### ISSUE TITLE
Проблема з конвертацією валюти. Зчитування данних з одного рядка

### ISSUE THREAD

**Issue by oleksin966** [volkovskey/exchange-rates-tg-bot#13]
**100 гривень 20 злотих** ---> Хлопці, то несерйозна робота! Бот в цілому хороший, але коли я вводжу         
**100 гривень 20 злотих** то в результаті отримую наступне:

**🇵🇱20.00 PLN**

...

**🇺🇦20.00 UAH** <--- тут мало бути **🇺🇦100.00 UAH**
...

Короче самі все бачите. Повинні виправити, бо це несерйозно.

**Comment by vladikko** [comment]
Ви можете поставити будь-який роздільник, і бот працюватиме коректно
Наприклад:
100 грн, 20 злотих

100 грн та 20 злотих

**Comment by volkovskey** [comment]
Поки що вважаємо, що витрачати зусилля на цей баг не доречно.
